language: groovy
jdk:
- oraclejdk7
before_script:
- rm -rf target
branches:
  only:
  - master
script: ./travis-build.sh
sudo: false
cache:
  directories:
  - $HOME/.gradle
env:
  global:
  - GIT_NAME="Robert Oschwald"
  - GIT_EMAIL="robertoschwald@gmail.com"
  - secure: QgwDKgm+TFRpt6fnAjbI4MGmBOIqfCm0ycyIom927aZPvhp4fzzI6wGIN06RTAPNao95BnV7TwSgonRExPfqIMCrMzDj4BXVYkK9uXUXTUPYw24+9cEv2ZvnyEurg/MR2ajpu3MHtam+7uGO8mh4pYq+693RpiU+IZFkB5vPWcM=
  - secure: mRX4Ye6O4iHcxV48DD8Oaz+7FmrN7vMf67g3Ym24zfzLLaxbl77z0XCMQYblU4s/OBqP9BNo4Y7v6HzCxJyWwMIRqz9txk/DkUUAzTSYHIxQwJqnZTdZNjh9muVmvGuyyBj7z/IhBtKVhNDEXn+OW6f0tdiHeLnaAy6kAovvwCA=
  - secure: Dz7Flw3cPnG5HgGSb49xvfdu8knvokK3+yO665P8kO/5lgzKjftonQkemxDmcAoiJYmgxJRVXO842sQ8A4vy90h+WzLpJBUdJAEAF27FS5Tq6DyzxrFaOu87DSOdJXPthpMUd0z7+5+7fyoaRY6gPcWiDn2BZ9SqjoJ0sskd1cI=
